### ISSUE TITLE
New Here!Just look around . What Can I do to help

### ISSUE THREAD

**Issue by MichaelCali** [InternationalColorConsortium/RefIccMAX#12]

**Comment by 243750496** [comment]
how to calibrate my camer using iccmax? i had got to see there is a gui interface of lprof
Q1:so i thought whether there is a gui for iccmax.
Q2:i installed iccmax but cannot find any command or gui , what's wrong with my installation ?
Q3:i want to calibrate my camera with colorchecker digital sg 2015 edition, so what to do with my card and iccmax?
Q4:how to convert a cgats file to a cie files with a command or setting with gui?
![iccmax](https://cloud.githubusercontent.com/assets/6311930/26032753/84840724-38cd-11e7-94cb-41da2f1b43c5.png)
[ColorCheckerSG.txt](https://github.com/InternationalColorConsortium/RefIccMAX/files/999223/ColorCheckerSG.txt)

**Comment by maxderhak** [comment]
Hi,

I appreciate your interest in iccMAX.  iccMAX is not an application it is a framework upon which applications can be developed with examples and command line tools for developers to use to test with.  Therefore it cannot be directly used to create a camera profile.  Applications that could do this have yet to be created.

Regards,

Max Derhak (PhD)
Principal Scientist

**Comment by hypernewbie** [comment]
Honestly I think RefIccMAX can do with a good bit of code refactoring. I think I understand ICC profiles less after reading the reference implementation here.

**Comment by maxderhak** [comment]
What exactly would you suggest (details requested)?

**Comment by hypernewbie** [comment]
Sorry I didn't have time during my previous post to type up more detailed feedback.
I think the library can be significantly simplified.

1. There is too much overloading of classes with unnecessary class overloads and interfaces.
   Overloaded classes is good, but there's too much of everything. Eg. all the CIccCurve overloads
   including CIccTagParametricCurve, CIccTagCurve ...etc can all just be munged into one bigger
   CIccCurve function for code simplicity.

2. There is very little explanation of the spec itself; this would be invaluable in a reference
   implementation of a standard file format, which is the stated purpose of this repository. Most
   of the docs are just "process comments" such as "Purpose: The parametric curve type tag".
   It would be most helpful to explain more useful format related things such as what this curve can
   contain, what do the coefficients mean...etc. I got that from reading the code for a while, but I
   feel the style of code documentation fights against me doing that

3. Code logic is split everywhere and needlessly convoluted. There is a lot of case-bash code: if
   this or this but not this then this else that then this or this or that. I think better design
   can mitigate the need for this significantly. The xform application stack code in Cmm is very
   convoluted with Apply factory copies, it's very own iterator for some reason. This can be
   simplified to a flat xforms[] array then xforms[n++] = MyXForm, then Cmm_Apply( xform, n ), and
   the entire IccCmm class deleted.

4. Exposure of internal members is very inconsistent. It is of help for my usecase for a library
   that can load ICC into a bunch of data structures and help me understand it and access the data.
   The loading of data structures is very good here and runs fast. The accessing bit is sort of
   wierd. For instance, I had to make a a hack class class MyCIccXformMatrix : public
   CIccXformMatrixTRC in order to access the protected matrix. Why isn't there a GetMatrix that's
   public here?

5. There is case-bash logic everywhere, with little clarification or justification. If dest space is
   this, and there's this other tag, why do I have to set this pointer to some random other tag?
   Please point to the ICC file format spec that raises the need for this?

Hope this helps, and thanks for the library!
